# Generated by Django 5.1 on 2025-11-27 03:15

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_fundraiser_owner_pledge_supporter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='anonymous',
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='invite_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='supporters',
            field=models.ManyToManyField(blank=True, related_name='supported_fundraisers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pledge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pledge',
            name='type',
            field=models.CharField(choices=[('time', 'Time'), ('words', 'Words')], default='time', max_length=10),
        ),
    ]
