# Generated by Django 5.1 on 2025-11-27 03:50

from django.db import migrations, models
import secrets


def populate_invite_codes(apps, schema_editor):
    Fundraiser = apps.get_model('fundraisers', 'Fundraiser')
    # generate a unique invite_code for any fundraiser without one
    for f in Fundraiser.objects.all():
        if not f.invite_code:
            token = secrets.token_urlsafe(8)
            # ensure uniqueness
            while Fundraiser.objects.filter(invite_code=token).exists():
                token = secrets.token_urlsafe(8)
            f.invite_code = token
            f.save(update_fields=['invite_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0003_remove_pledge_anonymous_fundraiser_invite_code_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_invite_codes),
        migrations.AlterField(
            model_name='fundraiser',
            name='goal',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='invite_code',
            field=models.CharField(blank=True, editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
