# Generated by Django 5.1 on 2025-11-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0004_alter_fundraiser_goal_alter_fundraiser_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='amount',
        ),
        migrations.AddField(
            model_name='pledge',
            name='action',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pledge',
            name='hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
