# Generated by Django 5.1 on 2025-11-29 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0005_remove_pledge_amount_pledge_action_pledge_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraiser',
            name='invite_code',
        ),
    ]
