# Generated by Django 5.1 on 2025-12-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0006_remove_fundraiser_invite_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraiser',
            name='goal',
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='goal_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='goal_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
