# Generated by Django 5.1 on 2026-02-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0008_mymodel_alter_fundraiser_image_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='checklist',
            field=models.JSONField(blank=True, default=list, help_text='List of tasks for the fundraiser'),
        ),
    ]
